# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 235)
        self.lineEdit_User = QtWidgets.QLineEdit(Form)
        self.lineEdit_User.setGeometry(QtCore.QRect(90, 40, 171, 31))
        self.lineEdit_User.setObjectName("lineEdit_User")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 50, 72, 15))
        self.label.setObjectName("label")
        self.pushButton_Login = QtWidgets.QPushButton(Form)
        self.pushButton_Login.setGeometry(QtCore.QRect(130, 150, 111, 41))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.lineEdit_Path = QtWidgets.QLineEdit(Form)
        self.lineEdit_Path.setGeometry(QtCore.QRect(90, 100, 171, 31))
        self.lineEdit_Path.setObjectName("lineEdit_Path")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 72, 15))
        self.label_2.setObjectName("label_2")
        self.pushButton_Save = QtWidgets.QPushButton(Form)
        self.pushButton_Save.setGeometry(QtCore.QRect(270, 100, 81, 31))
        self.pushButton_Save.setObjectName("pushButton_Save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "User"))
        self.pushButton_Login.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Path"))
        self.pushButton_Save.setText(_translate("Form", "Save"))
